pipeline:
  build:
    image: mesalocklinux/build-mesalock-linux
    pull: true
    commands:
      - export PYPY_USESSION_DIR=$(pwd)/pypy-usession-dir
      - mkdir pypy-usession-dir
      - /bin/bash -c "make pypy-c"
  package:
    image: mesalocklinux/build-mesalock-linux
    commands:
      - export PYPY_USESSION_DIR=$(pwd)/pypy-usession-dir
      - pypy pypy/tool/release/package.py --archive-name mesapy --targetdir . --without-cffi
